# Generated by Django 2.1.4 on 2019-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro', '0002_auto_20190217_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='explanation',
            field=models.CharField(max_length=200),
        ),
    ]
